#!/usr/bin/env node
/**
 * migrate-excel.js
 * Reads Διατροφή.xlsx and writes two SQL files:
 *   supabase/migration_002_ingredients.sql
 *   supabase/migration_003_recipes.sql
 *
 * Usage:
 *   node supabase/migrate-excel.js
 *
 * The Excel file must be at: supabase/Διατροφή.xlsx
 */

import pkg from 'xlsx'
const { readFile, utils } = pkg
const XLSX = { readFile, utils }
import { writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const EXCEL_PATH = join(__dirname, 'Διατροφή.xlsx')

// ── helpers ──────────────────────────────────────────────────────────────────

function n(val, fallback = 0) {
  const v = parseFloat(val)
  return isNaN(v) ? fallback : v
}

function sql(val) {
  if (val === null || val === undefined || val === '') return 'NULL'
  return `'${String(val).replace(/'/g, "''")}'`
}

function num(val) {
  const v = parseFloat(val)
  return isNaN(v) ? 'NULL' : String(v)
}

// ── load workbook ─────────────────────────────────────────────────────────────

console.log(`Reading ${EXCEL_PATH}…`)
const wb = XLSX.readFile(EXCEL_PATH)

// ── Sheet: Υλικά → ingredients ───────────────────────────────────────────────

const ylika = XLSX.utils.sheet_to_json(wb.Sheets['Υλικά'], { defval: '' })

console.log(`Found ${ylika.length} ingredients in Υλικά`)

const ingredientLines = ylika
  .filter(row => row['id'] && row['Όνομα'])
  .map(row => {
    const id       = parseInt(row['id'])
    const name     = sql(row['Όνομα'])
    const category = sql(row['Κατηγορία'])
    const unit     = sql(row['Μονάδα'] || 'gr')
    const refQty   = num(row['Ποσότητα αναφοράς']) || '100'
    const calories = num(row['θερμίδες ονομαστικές'])
    const protein  = num(row['Πρωτεΐνες g'])
    const carbs    = num(row['Υδατάνθρακες g'])
    const fat      = num(row['Λίπη g'])
    const sodium   = num(row['Νάτριο mg'])
    const potassium= num(row['Κάλιο mg'])

    return `(${id}, ${name}, ${category}, ${unit}, ${refQty}, ${calories}, ${protein}, ${carbs}, ${fat}, ${sodium}, ${potassium})`
  })

const ingredientsSql = `-- ============================================================
-- migration_002_ingredients.sql
-- Generated by migrate-excel.js — ${new Date().toISOString()}
-- ============================================================

truncate table public.recipe_items restart identity cascade;
truncate table public.recipes restart identity cascade;
truncate table public.ingredients restart identity cascade;

insert into public.ingredients
  (id, name, category, unit, ref_quantity, calories, protein_g, carbs_g, fat_g, sodium_mg, potassium_mg)
values
${ingredientLines.join(',\n')};

-- Reset sequence so new inserts don't collide
select setval('public.ingredients_id_seq', (select max(id) from public.ingredients));
`

const ingredientsPath = join(__dirname, 'migration_002_ingredients.sql')
writeFileSync(ingredientsPath, ingredientsSql, 'utf8')
console.log(`✓ Written: ${ingredientsPath}`)

// ── Sheet: ΣυνδΑθρ → recipes (one row per recipe) ────────────────────────────

const syndAthr = XLSX.utils.sheet_to_json(wb.Sheets['ΣυνδΑθρ'], { defval: '' })

// Deduplicate by name (ΣυνδΑθρ has one row per recipe)
const recipeMap = new Map()
syndAthr.forEach((row, idx) => {
  const name = row['Συνδυασμός']
  if (!name || recipeMap.has(name)) return
  recipeMap.set(name, {
    id:       idx + 1,
    name,
    weight:   num(row['Βάρος gr']),
    servings: parseInt(row['Μερίδες']) || 1,
    unit:     row['Μονάδα'] ? sql(row['Μονάδα']) : sql('gr'),
  })
})

console.log(`Found ${recipeMap.size} recipes in ΣυνδΑθρ`)

const recipeLines = [...recipeMap.values()].map(r =>
  `(${r.id}, ${sql(r.name)}, ${r.weight}, ${r.servings}, ${r.unit})`
)

// ── Sheet: Συνδυασμοί → recipe_items ─────────────────────────────────────────

const syndSheet = XLSX.utils.sheet_to_json(wb.Sheets['Συνδυασμοί'], { defval: '' })

// Build ingredient lookup: name → id
const ingredientByName = new Map()
ylika.forEach(row => {
  if (row['Όνομα'] && row['id']) {
    ingredientByName.set(String(row['Όνομα']).trim(), parseInt(row['id']))
  }
})

// Build recipe lookup: name → id
const recipeByName = new Map([...recipeMap.entries()].map(([name, r]) => [name, r.id]))

const recipeItemLines = []
let itemId = 1
let skipped = 0

syndSheet.forEach(row => {
  const recipeName = row['Όνομα']
  const ingredientName = row['Υλικά']
  const qty = row['Ποσότητα']
  const unit = row['Μονάδα']

  const recipeId = recipeByName.get(recipeName)
  const ingredientId = ingredientByName.get(String(ingredientName).trim())

  if (!recipeId || !ingredientId || !qty) {
    if (recipeName) skipped++
    return
  }

  recipeItemLines.push(
    `(${itemId++}, ${recipeId}, ${ingredientId}, ${num(qty)}, ${sql(unit || 'gr')})`
  )
})

if (skipped > 0) {
  console.warn(`⚠ Skipped ${skipped} recipe_item rows (missing recipe/ingredient match)`)
}
console.log(`Found ${recipeItemLines.length} recipe items`)

const recipesSql = `-- ============================================================
-- migration_003_recipes.sql
-- Generated by migrate-excel.js — ${new Date().toISOString()}
-- ============================================================

insert into public.recipes
  (id, name, total_weight_g, servings, unit)
values
${recipeLines.join(',\n')};

select setval('public.recipes_id_seq', (select max(id) from public.recipes));

insert into public.recipe_items
  (id, recipe_id, ingredient_id, quantity, unit)
values
${recipeItemLines.join(',\n')};

select setval('public.recipe_items_id_seq', (select max(id) from public.recipe_items));
`

const recipesPath = join(__dirname, 'migration_003_recipes.sql')
writeFileSync(recipesPath, recipesSql, 'utf8')
console.log(`✓ Written: ${recipesPath}`)

console.log('\n✅ Done. Now run these in Supabase SQL Editor (in order):')
console.log('   1. supabase/migration_002_ingredients.sql')
console.log('   2. supabase/migration_003_recipes.sql')
